/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,jsx}"],
  safelist: [
    "btn-danger",
    "btn-outline-danger",

    "btn-primary",
    "btn-outline-primary",
    "btn-primary-light",

    "fill-black",
    "fill-white",
    "fill-primary",
    "fill-secondary",
    "fill-primaryLight",
    "fill-secondaryLight",

    "btn-secondary",
    "btn-secondary-light",
    "btn-outline-secondary",

    "btn-text-primary",
    "btn-text-secondary",
    "btn-text-default",

    "btn-default",
    "btn-outline-default",

    "small",
    "medium",
    "large",

    "text-small",
    "text-medium",
    "text-large",
    "text-primary",
    "text-secondary",
    "text-white",
    "text-grayDefault",

    "font-bold",
    "font-normal",
    "font-semibold",

    "title-h1",
    "title-h2",
    "title-h3",
    "title-h4",
    "title-h5",
    "title-h6",

    "bg-primary",
    "bg-default",
    "bg-secondary",
    "bg-danger",
    "bg-primaryLight",
    "bg-defaultLight",
    "bg-secondaryLight",
    "bg-dangerLight",

    "card",
    "card-primary",

    "p-1",
    "p-2",
    "p-3",
    "p-4",

    "text-3xl",
    "text-4xl",
    "text-5xl",
    "text-6xl",

    "text-semibold",

    "w-0",
    "w-0.5",
    "w-1",
    "w-1.5",
    "w-2",
    "w-2.5",
    "w-3",
    "w-3.5",
    "w-4",
    "w-5",
    "w-6",
    "w-7",
    "w-8",
    "w-9",
    "w-10",
    "w-11",
    "w-12",
    "w-14",
    "w-16",
    "w-20",
    "w-24",
    "w-28",
    "w-32",
    "w-36",
    "w-40",
    "w-44",
    "w-48",
    "w-52",
    "w-56",
    "w-60",
    "w-64",
    "w-72",
    "w-80",
    "w-96",
    "w-auto",
    "w-1/2",
    "w-1/3",
    "w-2/3",
    "w-1/4",
    "w-2/4",
    "w-3/4",
    "w-1/5",
    "w-2/5",
    "w-3/5",
    "w-4/5",
    "w-1/6",
    "w-2/6",
    "w-3/6",
    "w-4/6",
    "w-5/6",
    "w-1/12",
    "w-2/12",
    "w-3/12",
    "w-4/12",
    "w-5/12",
    "w-6/12",
    "w-7/12",
    "w-8/12",
    "w-9/12",
    "w-10/12",
    "w-11/12",
    "w-full",
    "w-screen",
    "w-min",
    "w-max",
    "w-fit",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#00283D",
        primaryLight: "#4C5E73",
        primaryDark: "#001622",
        secondary: "#1e7b85",
        secondaryDark: "#14605a",
        secondaryLight: "#59a7a4",
        dark: "#0D1426",
        iconGray: "#E4E6F0",
        listBlue: "#EBEDF7",
        textGray: "#C4C6D3",
        darkBlue: "#0D247F",
        default: "#F2F3F4",
        defaultLight: "#E6E7E807",
        danger: "#DD2D2D",
        dangerLight: "#DD2D2D07",
        warning: "#FFAC32",
        warningLight: "#FFAC3207",
        success: "#14AD5B",
        successLight: "#14AD5B07",
        info: "#4099D9",
        infoLight: "#4099D907",
        white: "#FFFFFF",
        indigo: "#7D8AC9",
        gray01: "#FEFEFE",
        gray1: "#F2F3F4",
        gray15: "#d9d9d9",
        gray2: "#AAADB6",
        gray3: "#757986",
        gray4: "#656565",
        backdrop: "#0000009c",
      },
    },
  },
  plugins: [],
};
